version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli  
  build:
    commands:
      - echo Build started on `date`
      - ng build --prod --aot
  post_build:
     commands:
<<<<<<< HEAD
      - aws s3 cp dist/e-angaadi-web s3://eangaadi --recursive
=======
      - aws s3 cp dist/e-angaadi-web s3://Eangaadi --recursive
>>>>>>> 6f2b439c4e47d238261b518db3da79fc737aa865
      - echo Build completed on `date`      