version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli  
  build:
    commands:
      - echo Build started on `date`
      - ng build --prod --aot
  # post_build:
  #    commands:
  #     - aws s3 cp dist/e-angaadi s3://eangaadi --recursive
  #     - echo Build completed on `date`      
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/e-angaadi