import { Product } from '../models/product';
import { ProductGroup } from '../models/product-group';

export const PRODUCT_GROUPS: ProductGroup[] = [
  {
    active: true,
    code: 'veggie',
    order: 90,
    key: 'grp.veggie',
    title: 'Vegetables',
  },
  {
    active: true,
    code: 'grain',
    order: 20,
    key: 'grp.grain',
    title: 'Grains',
  },
  {
    active: false,
    code: 'beverage',
    order: 50,
    key: 'grp.beverage',
    title: 'Beverages',
  },
  {
    active: true,
    code: 'pulse',
    order: 10,
    key: 'grp.pulse',
    title: 'Pulses',
  },
  {
    active: true,
    code: 'fruit',
    order: 80,
    key: 'grp.fruit',
    title: 'Fruits',
  },
  {
    active: true,
    code: 'spicies',
    order: 40,
    key: 'grp.spicies',
    title: 'Spicies',
  },
  {
    active: true,
    code: 'flour',
    order: 30,
    key: 'grp.flour',
    title: 'Flours',
  },
  {
    active: true,
    code: 'snack',
    order: 70,
    key: 'grp.snack',
    title: 'Snacks',
  },
  {
    active: true,
    code: 'toiletries',
    order: 60,
    key: 'grp.toiletries',
    title: 'Toiletry',
  },
  {
    active: true,
    code: 'other',
    order: 100,
    key: 'grp.others',
    title: 'Others',
  },
];

export const PRODUCTS: Product[] = [
  {
    img: '/shopper/grains.png',
    code: 'brown_rice',
    submetric: 'kg',
    names: '',
    brand: '',
    group: 'grain',
    order: 50,
    key: 'grain.brown_rice',
    metric: 'solid',
    title: 'Brown rice ',
  },
  {
    img: '/shopper/grains.png',
    code: 'basmati_rice',
    submetric: 'kg',
    names: '',
    brand: '',
    group: 'grain',
    order: 40,
    key: 'grain.basmathi_rice',
    metric: 'solid',
    title: 'Basmati rice ',
  },
  {
    img: '/shopper/horse_gram.png',
    code: 'horse_gram',
    submetric: 'kg',
    names: '',
    brand: '',
    group: 'pulse',
    order: 120,
    key: 'pulse.horse_gram',
    metric: 'solid',
    title: 'Horse Gram ',
  },
  {
    img: '/shopper/grains.png',
    code: 'boiled_rice',
    submetric: 'kg',
    names: '',
    brand: '',
    group: 'grain',
    order: 30,
    key: 'grain.boiled_rice',
    metric: 'solid',
    title: 'Boiled rice ',
  },
  {
    img: '/shopper/toor_dal.png',
    code: 'thoor_dhal',
    submetric: 'kg',
    names: '',
    brand: '',
    group: 'pulse',
    order: 10,
    key: 'pulse.thoor_dhal',
    metric: 'solid',
    title: 'Thoor Dhal',
  },
  {
    img: '/shopper/grains.png',
    code: 'idly_rice',
    submetric: 'kg',
    names: '',
    brand: '',
    group: 'grain',
    order: 60,
    key: 'grain.idly_rice',
    metric: 'solid',
    title: 'Idli rice',
  },
  {
    img: '/shopper/pulses.png',
    code: 'moong_dhal',
    submetric: 'kg',
    names: '',
    brand: '',
    group: 'pulse',
    order: 100,
    key: 'pulse.moong_dhal',
    metric: 'solid',
    title: 'Moong Dhal ',
  },
  {
    img: '/shopper/pulses.png',
    code: 'peanut',
    submetric: 'kg',
    names: '',
    brand: '',
    group: 'pulse',
    order: 130,
    key: 'pulse.peanut',
    metric: 'solid',
    title: 'Peanut',
  },
  {
    img: '/shopper/pulses.png',
    code: 'chenna_dhal',
    submetric: 'kg',
    names: '',
    brand: '',
    group: 'pulse',
    order: 20,
    key: 'pulse.chenna_dhal',
    metric: 'solid',
    title: 'Chenna Dhal',
  },
  {
    img: '/shopper/grains.png',
    code: 'red_rice',
    submetric: 'kg',
    names: '',
    brand: '',
    group: 'grain',
    order: 70,
    key: 'grain.red_rice',
    metric: 'solid',
    title: 'Red rice',
  },
  {
    img: '/shopper/grains.png',
    code: 'raw_rice',
    submetric: 'kg',
    names: '',
    brand: '',
    group: 'grain',
    order: 10,
    key: 'grain.raw_rice',
    metric: 'solid',
    title: 'Raw rice ',
  },
  {
    img: '/shopper/pulses.png',
    code: 'urud_dhal',
    submetric: 'kg',
    names: '',
    brand: '',
    group: 'pulse',
    order: 30,
    key: 'pulse.urud_dhal',
    metric: 'solid',
    title: 'Urud Dhal',
  },
  {
    img: '/shopper/pulses.png',
    code: 'fried_gram',
    submetric: 'kg',
    names: '',
    brand: '',
    group: 'pulse',
    order: 140,
    key: 'pulse.fried_gram',
    metric: 'solid',
    title: 'Fried gram',
  },
  {
    img: '/shopper/pulses.png',
    code: 'brown_chickpeas_dhal',
    submetric: 'kg',
    names: '',
    brand: '',
    group: 'pulse',
    order: 90,
    key: 'pulse.brown_chickpeas_dhal',
    metric: 'solid',
    title: 'Kala Chana ',
  },
  {
    img: '/shopper/pulses.png',
    code: 'chickpeas_dhal',
    submetric: 'kg',
    names: '',
    brand: '',
    group: 'pulse',
    order: 80,
    key: 'pulse.chickpeas_dhal',
    metric: 'solid',
    title: 'Chick Peas ',
  },
  {
    img: '/shopper/green_gram.png',
    code: 'greengram_dhal',
    submetric: 'kg',
    names: 'Whole Moong Dhal',
    brand: '',
    group: 'pulse',
    order: 70,
    key: 'pulse.greengram_dhal',
    metric: 'solid',
    title: 'Green Gram ',
  },
  {
    img: '/shopper/pulses.png',
    code: 'kidney_bean',
    submetric: 'kg',
    names: 'Rajma',
    brand: '',
    group: 'pulse',
    order: 110,
    key: 'pulse.kidney_dhal',
    metric: 'solid',
    title: 'Kidney Beans',
  },
  {
    img: '/shopper/grains.png',
    code: 'ragi',
    submetric: 'kg',
    names: '',
    brand: '',
    group: 'grain',
    order: 90,
    key: 'grain.ragi',
    metric: 'solid',
    title: 'Ragi',
  },
  {
    img: '/shopper/pulses.png',
    code: 'masoor_dhal',
    submetric: 'kg',
    names: 'Red Lentils',
    brand: '',
    group: 'pulse',
    order: 40,
    key: 'pulse.masoor_dhal',
    metric: 'solid',
    title: 'Masoor Dhal ',
  },
  {
    img: '/shopper/pulses.png',
    code: 'black_urud_dhal',
    submetric: 'kg',
    names: '',
    brand: '',
    group: 'pulse',
    order: 60,
    key: 'pulse.black_urud_dhal',
    metric: 'solid',
    title: 'Black Urud Dhal ',
  },
  {
    img: '/shopper/grains.png',
    code: 'wheat',
    submetric: 'kg',
    names: '',
    brand: '',
    group: 'grain',
    order: 80,
    key: 'grain.wheat',
    metric: 'solid',
    title: 'Wheat',
  },
  {
    img: '/shopper/pulses.png',
    code: 'urud_split_dhal',
    submetric: 'gram',
    names: '',
    brand: '',
    group: 'pulse',
    order: 50,
    key: 'pulse.urud_split_dhal',
    metric: 'solid',
    title: 'Split Urud dhal ',
  },
];
